In [1]:
import numpy as np

In [2]:
np.array([1,2,4,5,6])

array([1, 2, 4, 5, 6])

In [4]:
my_array=np.array(["manoj","kk","yash","sahil"])
my_array
print(my_array)

['manoj' 'kk' 'yash' 'sahil']


In [5]:
np.__version__

'1.16.4'

In [7]:
arr=np.array(100)
print(arr)
print(type(arr))

100
<class 'numpy.ndarray'>


In [9]:
ele=[1,4,5,7,8]
one_D=np.array(ele)
one_D


array([1, 4, 5, 7, 8])

In [10]:
elee=[[1,2,4],[14,7,8]]
two_D=np.array(elee)
print(two_D)

[[ 1  2  4]
 [14  7  8]]


In [11]:
print(one_D.ndim)
print(two_D.ndim)
three_D=np.array([[[1,2,3],[14,7,8]],[1,4,7],[7,8,5]])
print(three_D)
print(three_D.ndim)

1
2
[list([[1, 2, 3], [14, 7, 8]]) list([1, 4, 7]) list([7, 8, 5])]
1


In [13]:
one=np.ones(5,dtype=int)
print(one)

[1 1 1 1 1]


In [14]:
one=np.ones((5,5),dtype=float)
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
import sys

In [18]:
l=[1,4,5,2,6]
print(sys.getsizeof(1)*len(l))
m=np.array([1,4,5,2,6])
print(m.size*m.itemsize)

140
20


In [21]:
import time
l1=range(1,1000000)
l2=range(1,1000000)
a1=np.array(l1)
a2=np.array(l2)
strt=time.time()
res=[x+y for x,y in zip(l1,l2)]
print((time.time()-strt)*1000)
strt=time.time()
res=a1+a2
print((time.time()-strt)*1000)

271.7785835266113
31.241655349731445


In [22]:
arr=np.array([[1,4,5],[4,7,8]])
print(arr.shape)


(2, 3)


In [23]:
ar=np.random.rand(10)
print(ar)

[0.30588021 0.46323999 0.47193921 0.41404664 0.48554387 0.1137153
 0.0882639  0.85508325 0.13852408 0.98514653]


In [24]:
ae=np.random.rand(5,10)
print(ae)


[[0.26381855 0.394609   0.63102165 0.33249608 0.48416176 0.40553881
  0.55556455 0.46726479 0.95944586 0.50778976]
 [0.01229189 0.03947989 0.83677284 0.98829077 0.04341874 0.34547049
  0.53258869 0.2199264  0.78291724 0.82772842]
 [0.93296048 0.11133342 0.19346738 0.94319408 0.90670337 0.25791765
  0.90112015 0.66418276 0.12271785 0.83966083]
 [0.75141786 0.88543993 0.76567571 0.89777544 0.53548274 0.96623296
  0.83674637 0.50163651 0.66034789 0.64146297]
 [0.17743746 0.40470867 0.72627354 0.58722447 0.80227586 0.29868964
  0.74090595 0.98207031 0.16474486 0.37535045]]


In [25]:
a=np.random.randint(5,10,size=10)
print(a)

[7 8 5 8 6 7 7 9 8 5]


In [26]:
b=np.random.randint(5,10,size=(5,5))
print(b)

[[5 6 9 5 6]
 [6 7 5 9 7]
 [8 7 5 8 6]
 [9 5 7 9 7]
 [6 9 8 9 5]]


In [29]:
c=np.random.choice([1,4,8,5,7,9,52,4])
print(c)

9


In [30]:
d=np.random.choice([1,4,7,8,5,2,5,9,3],size=(5,5))
print(d)

[[2 2 7 2 2]
 [8 5 9 7 1]
 [7 4 1 5 2]
 [9 5 7 8 3]
 [8 5 5 7 2]]


In [31]:
x=np.random.randint(1,10,size=(5,5))
x

array([[2, 3, 6, 8, 9],
       [1, 3, 3, 6, 2],
       [2, 9, 6, 2, 7],
       [5, 8, 4, 6, 8],
       [4, 9, 2, 4, 9]])

In [32]:
x[1:4]

array([[1, 3, 3, 6, 2],
       [2, 9, 6, 2, 7],
       [5, 8, 4, 6, 8]])

In [33]:
x[1:4,:2]

array([[1, 3],
       [2, 9],
       [5, 8]])

In [36]:
x[:,::-1]

array([[9, 8, 6, 3, 2],
       [2, 6, 3, 3, 1],
       [7, 2, 6, 9, 2],
       [8, 6, 4, 8, 5],
       [9, 4, 2, 9, 4]])

In [39]:
x[0][1:4]

array([3, 6, 8])

In [40]:
x[x%5==0]

array([5])

In [41]:
x[x%2==0]


array([2, 6, 8, 6, 2, 2, 6, 2, 8, 4, 6, 8, 4, 2, 4])

In [42]:
x.shape

(5, 5)

In [43]:
x.ndim

2

In [44]:
x.size

25

In [46]:
x

array([[2, 3, 6, 8, 9],
       [1, 3, 3, 6, 2],
       [2, 9, 6, 2, 7],
       [5, 8, 4, 6, 8],
       [4, 9, 2, 4, 9]])

In [47]:
n=np.arange(1,10)
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x=n.reshape((3,3))

In [50]:
x.base

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x=np.random.randint(5,10,size=(2,3))
x

array([[9, 6, 7],
       [9, 6, 5]])

In [59]:
x.reshape(-1)

array([9, 6, 7, 9, 6, 5])

In [60]:
x=np.arange(5,9).reshape((2,2))
x

array([[5, 6],
       [7, 8]])

In [61]:
x.T


array([[5, 7],
       [6, 8]])

In [62]:
a=np.array([[1,4,7],[7,8,5],[1,4,5]])
a

array([[1, 4, 7],
       [7, 8, 5],
       [1, 4, 5]])

In [65]:
np.rot90(a,k=2)

array([[5, 4, 1],
       [5, 8, 7],
       [7, 4, 1]])

In [67]:
x=np.array([[1,4,7],[8,9,5]])
y=np.array([[7,8,4],[4,5,2]])
np.concatenate([x,y])

array([[1, 4, 7],
       [8, 9, 5],
       [7, 8, 4],
       [4, 5, 2]])

In [69]:
np.concatenate([x,y],axis=1)

array([[1, 4, 7, 7, 8, 4],
       [8, 9, 5, 4, 5, 2]])